### ISSUE TITLE
configure failed at cryptlib.h in MingW

### ISSUE THREAD

**Issue by shinchiro** [meganz/sdk#104]
Here is config.log

http://pastebin.com/KBMGqyYs

**Comment by wizzard** [comment]
Hello,

could you please get the latest MEGA SDK code and try to run ```build_sdk.sh``` script again?

**Comment by shinchiro** [comment]
I tried the latest commit but get 'Could not find libcryptopp' error 

http://pastebin.com/0tX8K6wB

fyi, this is my build environment: http://xhmikosr.1f0.de/tools/msys/

**Comment by shinchiro** [comment]
I give another try to solve this error. The error happen when you try create static build, so passing -y when running build_sdk.sh will solve the libcryptopp error

Rerun again and after that the script reported that termcap is not found. It turn out it missed line to build & install termcap after:
readline_win_pkg  $build_dir $install_dir

Edited it & run again and I get another error..winhttp.h is not found..This where I gave up since I cannot winhttp is difficult to get..seriously can it build without depend on winhttp?

**Comment by wizzard** [comment]
Hello,
sorry I didn't update this issue: the current "sdk_build.sh" script does not support Windows environment (I'm working on adding Windows support, but this will take some time).

Could you please try to use the default "configure" script to config and build MEGA SDK?

Regarding "termcap" issue: you can either try to configure MEGA SDK without example application (using --disable-examples configure option), or try to use http://gnuwin32.sourceforge.net/packages/readline.htm ReadLine package.

Please let me know how it works for you!

**Comment by shinchiro** [comment]
Nah, take your time..running configure works fine while linking to dependencies that has built with sdk_build script. But I puzzled with winhttp.h not found error as I cannot seem to find winhttp easily

**Comment by wizzard** [comment]
As far as I know winhttp.h (and winhttp.lib) are part of Windows SDK.

**Comment by shinchiro** [comment]
I got vs2013 install so the windows SDK existed. Here is errors I got from winhttp.h

http://pastie.org/private/ecbxe4nv3jvosnqzrdlqka

**Comment by wizzard** [comment]
Hello, I've just committed several changes to our ```build_sdk.sh``` script, now you should be able to build MEGA SDK and examples on MinGW platform.
To get WinHTTP header and library usable in MinGW environment either search in Google or you could use these two files: 
WinHTTP header: https://mega.nz/#!JoonQb4a!w2TpgFp1A5JASZruNmS-GMdbBBUXg5pFpIkF_PKktI4
WinHTTP library: https://mega.nz/#!8kJyBbJI!eTSlLzsmzOdBN_6Qz9P0FlP6YMuiGkZ-YuqKuor75IA

Put these two files into SDK project's root folder and run ```./contrib/ build_sdk.sh``` script.

**Comment by shinchiro** [comment]
I tried with latest commit to build this sdk under mingw again after putting winhttp files in the root. 

But I still cannot get it compiled. Most error came from Winhttp.h

**Comment by wizzard** [comment]
from what I read, we can't use the original winhttp.h header file in MinGW (as it contains Microsoft specific features). Take a look in the Internet for a “fixed” winhttp.h version (or download my file).

Please let me know if you have any other compilation issues. Thank you!

**Comment by shinchiro** [comment]
Thanx for the info & helps. I used your winhttp.h file previously and it failed. But after I replaced it with winhttp.h from mingw, voila it compiled successfully!

Just one issue I found. readline5.dll is not statically build with megacli so I need to place the dll under same directory
