### ISSUE TITLE
recurrent replacing of eml-files eating up space in Rubbish

### ISSUE THREAD

**Issue by brerra66it** [meganz/sdk#2700]
Hi, I have used `MEGAsync` for three Windows machines and uploaded hundred of `*.eml`-files to cloud. These are emails saved using Thunderbird, that I want to store for some reason.

I have noticed, that `MEGAsync` apparently cannot recognize whether file is the same an after each scan it happens to put old files to the Rubbish and upload new one. Despite the cloud storage and local copies looks okay, there is an issue with Rubbish storage.

For example, in the folder `MEGA\Rubbish\2025-02-18\2025-02-18 11.07.35.0\`
one can find sets of files of identical size of 5098 bytes with names:
- 2024-10-27_Rejection(1).eml
- 2024-10-27_Rejection(1)(1)(2).eml
- 2024-10-27_Rejection(2).eml
- 2024-10-27_Rejection(2)(1)(1)(1).eml
- 2024-10-27_Rejection(2)(2).eml
- 2024-10-27_Rejection(2)(2)(1)(1)(1).eml
- 2024-10-27_Rejection(3).eml

similar and exaggerated example can be seen on screenshot below, where multiple copies of the same 11755-byte file `2019-05-20 (26772484) Ihr Wechsel zu EnBW (Energie Baden-Württemberg) _ WB.eml` listed 46 times for some reason

![Image](https://github.com/user-attachments/assets/3d2168c6-c062-46a3-8636-e8868d41457d)

Thus, if one left `MEGAsync` unattended such Rubbish Bin can it up tens of Gb on every device. I also got warning from the cloud, that my quote of 50 Gb is full, while I only have 30 Gb of data stored. Other parts are multiple copies of `*.eml`-files. At the moment I have 8 Gb of Rubbish, contains 18688 Files and 2392 folders.

**Comment by sergiohs84** [comment]
Hi @brerra66it 

Since the reported issue is actually part of the logic of the SDK, we have transferred it to the SDK's repository.

As previously mentioned by @vmgaGH, the issue is already resolved in the [SDK's release v8.5.0](https://github.com/meganz/sdk/releases/tag/v8.5.0), as part of the SDK-4647. The next MEGAsync (v5.9.0) will include the patch, so you can expect to be fixed once you update the app 😃 

Before closing this ticket, let us reply what "frequently" means:

- "Frequently" is defined by the throttling update rate. By default, in next version, is 30 mins (in the future, it could be customizable through Settings, but not in this one), which means that any existing synced file which is updated and requires a new sync-upload, will wait up to 30 mins before being uploaded. If there are any new changes in that same file during the waiting time (while the updated file is waiting to be uploaded) it won't affect the waiting time: the file will still be uploaded after waiting 30 mins after the 1st change, and the upload will contain the latest changes. 
Example: 
1. The existing file is updated (change 1)
2. It waits in a queue to be uploaded after 30 mins
3. In minute 20:00, the same file changes again (change 2)
4. In minute 29:59, the file changes again (change 3)
5. In minute 30:00, the file is finally uploaded, containing the latest changes (change 3).

- Throttling affects all synced files, not just `.eml` files and it's only applied to sync-uploads, not sync-downloads.
- As the files in the Rubbish bin are created as recoverable old versions when a sync-transfer is triggered, this throttling mechanism, affecting uploads, also prevents the issue of creating new versions in the Rubbish bin.
- Remember that a local change triggers a sync-upload that updates the file in the cloud, so that file in the cloud is moved to the (remote) Rubbish bin before being replaced with the new local version. And the other way round: a remote change triggers a sync-download that updates the file in the local folder, so that file in the local folder is moved to local .debris/Rubbish before being replaced with the new remote version.
- If there are old versions both in local and remote debris folders, that's because that file has been changed both in the cloud and the local filesystem. This typically happens when there is a ping-pong effect due to syncs on different machines syncing the same remote folder.

Hope the behavior is clear. And once again, thank you for reporting the issue.

**Comment by brerra66it** [comment]
@sergiohs84 thanks for you answer. Though it all sounds very convincing, I do believe that the main issue is still not addressed. I foreseee that megasync still will do unnecessary syncs and load machines and servers for nothing. How is that lean?

Yes, introducing `throttling update rate` will reduce amount of generated rubbish, but it will not prevent bloody windows eml-file status change every scan. Unfortunatelly, bloody Windows behaviour will also became megasync issue. And we also not discussed what will happen if one enable version history, for example, to further escalate the problem.

In my perception, throttling update rate deals with symptoms, not with the underlying "windows-eml-ntfs-update". I do not want megasync to update my eml-files every half an hour. They are the same and perhaps one should consider special scenario for syncing that particular files on window or look for more elegant way to see if file actually changed, otherwise every 30 min (or other `throttling update rate`) mega will do useless stuff just because bloody windows index them each scan.

**Comment by lackovic** [comment]
I have one `.eml` file in my MEGA folder that I have not touched for years and it is constantly being synced.

I can see the same file being created every second under a different directory in the MEGA `Rubbish` folder.

This typically happens for a few hours at a time, then randomly stops, and then happens again after many days.

I have experienced this issue under different installations of Windows.

Using the latest version of MegaSync 5.13.0 on Windows 24H2.
