### ISSUE TITLE
Java examples not compiling

### ISSUE THREAD

**Issue by BullyWiiPlaza** [meganz/sdk#355]
I followed the instructions from [here](https://github.com/meganz/sdk/tree/master/examples/java) on Windows but I cannot successfully compile the project due to unresolved references:

```
>"C:\Program Files\Java\jdk1.8.0_92\bin\javac.exe" -d bin -sourcepath src/ src/nz/mega/bindingsample/SwingExample.java
src\nz\mega\bindingsample\SwingExample.java:42: error: cannot find symbol
import nz.mega.sdk.MegaApiJava;
                  ^
  symbol:   class MegaApiJava
  location: package nz.mega.sdk
src\nz\mega\bindingsample\SwingExample.java:43: error: cannot find symbol
import nz.mega.sdk.MegaApiSwing;
                  ^
  symbol:   class MegaApiSwing
  location: package nz.mega.sdk
src\nz\mega\bindingsample\SwingExample.java:45: error: cannot find symbol
import nz.mega.sdk.MegaLoggerInterface;
                  ^
  symbol:   class MegaLoggerInterface
  location: package nz.mega.sdk
src\nz\mega\bindingsample\SwingExample.java:48: error: cannot find symbol
import nz.mega.sdk.MegaRequestListenerInterface;
                  ^
  symbol:   class MegaRequestListenerInterface
  location: package nz.mega.sdk
src\nz\mega\bindingsample\SwingExample.java:56: error: cannot find symbol
public class SwingExample extends JFrame implements MegaRequestListenerInterface, MegaLoggerInterface {
                                                    ^
  symbol: class MegaRequestListenerInterface
src\nz\mega\bindingsample\SwingExample.java:56: error: cannot find symbol
public class SwingExample extends JFrame implements MegaRequestListenerInterface, MegaLoggerInterface {
                                                                                  ^
  symbol: class MegaLoggerInterface
src\nz\mega\bindingsample\SwingExample.java:61: error: cannot find symbol
    static MegaApiSwing megaApi = null;
           ^
  symbol:   class MegaApiSwing
  location: class SwingExample
src\nz\mega\bindingsample\SwingExample.java:295: error: cannot find symbol
    public void onRequestStart(MegaApiJava api, MegaRequest request) {
                               ^
  symbol:   class MegaApiJava
  location: class SwingExample
src\nz\mega\bindingsample\SwingExample.java:306: error: cannot find symbol
    public void onRequestUpdate(MegaApiJava api, MegaRequest request) {
                                ^
  symbol:   class MegaApiJava
  location: class SwingExample
src\nz\mega\bindingsample\SwingExample.java:322: error: cannot find symbol
    public void onRequestFinish(MegaApiJava api, MegaRequest request, MegaError e) {
                                ^
  symbol:   class MegaApiJava
  location: class SwingExample
src\nz\mega\bindingsample\SwingExample.java:367: error: cannot find symbol
    public void onRequestTemporaryError(MegaApiJava api, MegaRequest request, MegaError e) {
                                        ^
  symbol:   class MegaApiJava
  location: class SwingExample
src\nz\mega\bindingsample\SwingExample.java:108: error: cannot find symbol
        MegaApiSwing.setLoggerObject(this);
        ^
  symbol:   variable MegaApiSwing
  location: class SwingExample
src\nz\mega\bindingsample\SwingExample.java:109: error: cannot find symbol
        MegaApiSwing.setLogLevel(MegaApiSwing.LOG_LEVEL_MAX);
                                 ^
  symbol:   variable MegaApiSwing
  location: class SwingExample
src\nz\mega\bindingsample\SwingExample.java:109: error: cannot find symbol
        MegaApiSwing.setLogLevel(MegaApiSwing.LOG_LEVEL_MAX);
        ^
  symbol:   variable MegaApiSwing
  location: class SwingExample
src\nz\mega\bindingsample\SwingExample.java:113: error: cannot find symbol
            megaApi = new MegaApiSwing(SwingExample.APP_KEY, SwingExample.USER_AGENT, path);
                          ^
  symbol:   class MegaApiSwing
  location: class SwingExample
src\nz\mega\bindingsample\SwingExample.java:294: error: method does not override or implement a method from a supertype
    @Override
    ^
src\nz\mega\bindingsample\SwingExample.java:305: error: method does not override or implement a method from a supertype
    @Override
    ^
src\nz\mega\bindingsample\SwingExample.java:321: error: method does not override or implement a method from a supertype
    @Override
    ^
src\nz\mega\bindingsample\SwingExample.java:366: error: method does not override or implement a method from a supertype
    @Override
    ^
src\nz\mega\bindingsample\SwingExample.java:372: error: cannot find symbol
        MegaApiSwing.log(MegaApiSwing.LOG_LEVEL_INFO, message, "MainActivity");
                         ^
  symbol:   variable MegaApiSwing
  location: class SwingExample
src\nz\mega\bindingsample\SwingExample.java:372: error: cannot find symbol
        MegaApiSwing.log(MegaApiSwing.LOG_LEVEL_INFO, message, "MainActivity");
        ^
  symbol:   variable MegaApiSwing
  location: class SwingExample
src\nz\mega\bindingsample\SwingExample.java:375: error: method does not override or implement a method from a supertype
    @Override
    ^
22 errors
```

If I copy the Java bindings from `\sdk-master\bindings\java` to `\sdk-master\examples\java\src` I'm getting the following compilation errors:

```
>"C:\Program Files\Java\jdk1.8.0_92\bin\javac.exe" -d bin -sourcepath src/ src/nz/mega/bindingsample/SwingExample.java
src\nz\mega\sdk\MegaApiJava.java:969: error: cannot find symbol
        megaApi.resetPassword(email, hasMasterKey, createDelegateRequestListener(listener));
               ^
  symbol:   method resetPassword(String,boolean,MegaRequestListener)
  location: variable megaApi of type MegaApi
src\nz\mega\sdk\MegaApiJava.java:988: error: cannot find symbol
        megaApi.queryResetPasswordLink(link, createDelegateRequestListener(listener));
               ^
  symbol:   method queryResetPasswordLink(String,MegaRequestListener)
  location: variable megaApi of type MegaApi
src\nz\mega\sdk\MegaApiJava.java:1017: error: cannot find symbol
        megaApi.confirmResetPassword(link, newPwd, masterKey, createDelegateRequestListener(listener));
               ^
  symbol:   method confirmResetPassword(String,String,String,MegaRequestListener)
  location: variable megaApi of type MegaApi
src\nz\mega\sdk\MegaApiJava.java:1033: error: cannot find symbol
        megaApi.cancelAccount(createDelegateRequestListener(listener));
               ^
  symbol:   method cancelAccount(MegaRequestListener)
  location: variable megaApi of type MegaApi
src\nz\mega\sdk\MegaApiJava.java:1057: error: cannot find symbol
        megaApi.confirmCancelAccount(link, pwd, createDelegateRequestListener(listener));
               ^
  symbol:   method confirmCancelAccount(String,String,MegaRequestListener)
  location: variable megaApi of type MegaApi
src\nz\mega\sdk\MegaApiJava.java:1075: error: cannot find symbol
        megaApi.changeEmail(email, createDelegateRequestListener(listener));
               ^
  symbol:   method changeEmail(String,MegaRequestListener)
  location: variable megaApi of type MegaApi
src\nz\mega\sdk\MegaApiJava.java:1096: error: cannot find symbol
        megaApi.queryChangeEmailLink(link, createDelegateRequestListener(listener));
               ^
  symbol:   method queryChangeEmailLink(String,MegaRequestListener)
  location: variable megaApi of type MegaApi
src\nz\mega\sdk\MegaApiJava.java:1116: error: cannot find symbol
        megaApi.confirmChangeEmail(link, pwd, createDelegateRequestListener(listener));
               ^
  symbol:   method confirmChangeEmail(String,String,MegaRequestListener)
  location: variable megaApi of type MegaApi
src\nz\mega\sdk\MegaApiJava.java:1969: error: cannot find symbol
        return megaApi.getUserAvatarColor(user);
                      ^
  symbol:   method getUserAvatarColor(MegaUser)
  location: variable megaApi of type MegaApi
src\nz\mega\sdk\MegaApiJava.java:1985: error: cannot find symbol
        return megaApi.getUserAvatarColor(userhandle);
                      ^
  symbol:   method getUserAvatarColor(String)
  location: variable megaApi of type MegaApi
src\nz\mega\sdk\MegaApiJava.java:3430: error: cannot find symbol
        megaApi.enableTransferResumption();
               ^
  symbol:   method enableTransferResumption()
  location: variable megaApi of type MegaApi
src\nz\mega\sdk\MegaApiJava.java:3466: error: cannot find symbol
        megaApi.enableTransferResumption(loggedOutId);
               ^
  symbol:   method enableTransferResumption(String)
  location: variable megaApi of type MegaApi
src\nz\mega\sdk\MegaApiJava.java:3477: error: cannot find symbol
        megaApi.disableTransferResumption();
               ^
  symbol:   method disableTransferResumption()
  location: variable megaApi of type MegaApi
src\nz\mega\sdk\MegaApiJava.java:3490: error: cannot find symbol
        megaApi.disableTransferResumption(loggedOutId);
               ^
  symbol:   method disableTransferResumption(String)
  location: variable megaApi of type MegaApi
src\nz\mega\sdk\MegaApiJava.java:4694: error: cannot find symbol
        return megaApi.authorizeNode(node);
                      ^
  symbol:   method authorizeNode(MegaNode)
  location: variable megaApi of type MegaApi
15 errors
```

I also found that `MegaApi.java` does not contain those methods so of course trying to call them is invalid.

Please fix the project setup or instructions since it doesn't work out. I just want to use the API in Java so providing a `Maven` dependency would be great. Thanks a lot.

**Comment by sergiohs84** [comment]
Hi @BullyWiiPlaza 

The pre-built Java bindings seem to be out of date, that's the reason for both of your compilation errors. We will update them shortly, so you can download them again and those errors should go away. We'll let you know here.

Thank you for noticing.

**Comment by bvivek35** [comment]
Hi @BullyWiiPlaza 
I was trying to run the java examples as you were. The pre-built ones are out of date, but upon copying the sources in bindings/java/nz/mega/sdk/* to examples/java/src/nz/mega/sdk/ the compilation succeeded and indeed the examples run.

**Comment by A7F** [comment]
are the pre built java bindings still out of date? Asking because some methods used in MegaApiJava seems not available inside class MegaApi; methods like:

resetPassword
queryResetPasswordLink
confirmResetPassword
cancelAccount 

and so on...
so what sould I do? I just need a .jar file to include it inside eclipse projects so that's why I tried to compile the example. What should I copy, and where? Inside folder bindings/java/nz/mega/sdk/ there isn't MegaApi class: is that file the new MegaApiJava?

(a maven dependancy would be awesome, pretty sure will save a lot of issues)

**Comment by javiserrano** [comment]
We are just updating them. There is already pull request that should solve that problem. It will be merged into the `develop` branch as soon as it's reviewed, and a bit later into `master`.

If you use the prebuilt libraries in the instructions of the `update-java-example-win` branch, you shouldn't have that problem:
https://github.com/meganz/sdk/blob/update-java-example-win/examples/java/README.md

Take into account that the new libraries have been build with Visual Studio 2015, so it's needed to install the corresponding Microsoft Redistributable Package to use them.

**Comment by javiserrano** [comment]
The changes have just been pushed into `develop` so you can already use the instructions and prebuilt libraries on that branch:
https://github.com/meganz/sdk/blob/develop/examples/java/README.md

**Comment by Frattaglia** [comment]
I may be dumb, but I still can't use the Java examples (I'm on Windows)

**Comment by javiserrano** [comment]
Hi @Frattaglia 

I have just repeated the steps in the instructions to run the examples and they have worked for me.

It seems that you can't load the native libraries, so please check that you have `mega.dll`, `libcurl.dll`, etc. in `C:\Users\Frattaglia\workspace\project\libs` and that you have added that folder to the PATH environment variable in the same console before running the example: 
`set PATH=%PATH%;C:\Users\Frattaglia\workspace\project\libs`.

Check that you are using a 32 bit version of the JDK. If you are using a 64 bit version, you have to replace the libraries in your `libs` folder by the ones that you should have in `libs/x64`.

Also, please check that you have the Visual Studio 2015 Redistributable Package installed in your system for the same arch of your JDK and the MEGA libraries that you are using (32 or 64 bits).

**Comment by A7F** [comment]
what if my project is a maven project, where do I have to put libmegajava.so ? Do I have to refer that library somwhere in my pom file? I guess running the project on ubuntu only needs libmegajava.so , right?
