### ISSUE TITLE
Segmentation fault while executing lt-megasimplesync

### ISSUE THREAD

**Issue by nephilim1973** [meganz/sdk#60]
While executing...

./lt-megasimplesync /home/user1/MEGAsync /MEGAsync --lt-debug

as normal user, a "Segmentation fault" occurs. 

Same as "root" user (with a little bit more information...):

megasimplesync:examples/megasimplesync:93: libtool wrapper (GNU libtool) 2.4.2 Debian-2.4.2-1ubuntu1
megasimplesync:examples/megasimplesync:114: newargv[0]: /root/GIT/mega-sdk/examples/.libs/lt-megasimplesync
megasimplesync:examples/megasimplesync:104: newargv[1]: /home/user1/MEGAsync
megasimplesync:examples/megasimplesync:104: newargv[2]: /MEGAsync
Segmentation fault

STRACE:
[...]
munmap(0xb75f2000, 4096)                = 0                                                                                                                                         
clock_gettime(CLOCK_MONOTONIC, {4842599, 463314166}) = 0                                                                                                                            
send(6, "K\365\1\0\0\1\0\0\0\0\0\0\1g\3api\4mega\2co\2nz\0\0\1"..., 34, MSG_NOSIGNAL) = 34                                                                                          
clock_gettime(CLOCK_MONOTONIC, {4842599, 463420915}) = 0                                                                                                                            
--- SIGSEGV (Segmentation fault) @ 0 (0) ---                                                                                                                                        
+++ killed by SIGSEGV +++                                                                                                                                                           
Segmentation fault

EDIT:
By the way... megacli is running fine

**Comment by wizzard** [comment]
Hello, megasimplesync could be unstable on several platforms (we are currently migrating its code to the new API), could you please use ```megacli``` application for now? To synchronize local and remote folders please run ```megacli``` and execute ```loging [your email]``` following by ```sync [local folder] [remote folder]``` commands.

**Comment by nephilim1973** [comment]
Hi wizzard, it's you again... :-)

Thanks for information. But how I could automate "megacli" application ? I tried to pipe STDIN or text file to the application, but it does not work.

example:     "megacli < file.txt"

"megacli --help" is also not available.

Want to activate the app during system boot. Could I store the credentials and sync informations in a separate config file or is "megacli" just an interactive application ?

Regards and thanks a lot.

**Comment by wizzard** [comment]
Currently ```megacli``` does not support automation, this is an interactive application.

If you have GUI, you could use our MEGAsync application: https://mega.co.nz/#sync

Anyway, we will update ```megasimplesync``` soon, which you will be able to use during system boot.

**Comment by javiserrano** [comment]
I have fixed the crash in megasimplesync in the last commit (at least, I can't reproduce it anymore):
https://github.com/meganz/sdk/commit/383f974f492361b8607ba0735034af8640865ab3

The problem wasn't in megasimplesync, but in the network layer of the SDK.
@nephilim1973, Could you confirm if the problem is fixed for you?

**Comment by nephilim1973** [comment]
Hi Javi...
Many thanks. After your fix, the segmentation fault still occurs, but not so often... :-)

An example:

$ ./megasimplesync /MyFolder/BACKUP/ /MEGAsync/BACKUP/ --lt-debug
megasimplesync:examples/megasimplesync:93: libtool wrapper (GNU libtool) 2.4.2 Debian-2.4.2-1ubuntu1
megasimplesync:examples/megasimplesync:114: newargv[0]: /home/megasync/GIT/mega-sdk/examples/.libs/lt-megasimplesync
megasimplesync:examples/megasimplesync:104: newargv[1]: /MyFolder/BACKUP/
megasimplesync:examples/megasimplesync:104: newargv[2]: /MEGAsync/BACKUP/
Sync started !
Sync - local file addition detected: /MyFolder/BACKUP/weekly.tgz
Sync - local file addition detected: /MyFolder/BACKUP/daily.tgz
Sync is now active
Segmentation fault   <----  SEGFAULT !!!!


$ ./megasimplesync /MyFolder/BACKUP/ /MEGAsync/BACKUP/ --lt-debug
megasimplesync:examples/megasimplesync:93: libtool wrapper (GNU libtool) 2.4.2 Debian-2.4.2-1ubuntu1
megasimplesync:examples/megasimplesync:114: newargv[0]: /home/megasync/GIT/mega-sdk/examples/.libs/lt-megasimplesync
megasimplesync:examples/megasimplesync:104: newargv[1]: /MyFolder/BACKUP/
megasimplesync:examples/megasimplesync:104: newargv[2]: /MEGAsync/BACKUP/
Sync started !
Sync - local file addition detected: /MyFolder/BACKUP/weekly.tgz
Sync - local file addition detected: /MyFolder/BACKUP/daily.tgz
Sync is now active
Sync - requesting file /MyFolder/BACKUP/daily.tgz   <----  OK !!!! 
Sync - requesting file /MyFolder/BACKUP/weekly.tgz
Sync - state change of node  to Syncing
Sync - state change of node  to Pending
Sync - state change of node  to Syncing
Sync - state change of node  to Pending
Sync - state change of node daily.tgz to Pending
Sync - sending file /MyFolder/BACKUP/daily.tgz
Sync - state change of node weekly.tgz to Pending
Sync - sending file /MyFolder/BACKUP/weekly.tgz
Sync - state change of node daily.tgz to Syncing
Sync - state change of node  to Syncing
Sync - state change of node  to Pending
^C

Both commands were executed shortly after each other.
First time, the segfault occurs.
After this, megasimplesync carries out his work.

Regards Nephilim

**Comment by nephilim1973** [comment]
Additional information:

...
Sync started !
Sync - local file addition detected: ../MEGAsync/BACKUP/daily.tgz
Sync - local file addition detected: ../MEGAsync/BACKUP/weekly.tgz
Sync is now active
Segmentation fault

$ echo $?
139

Probably the error code helps.

**Comment by javiserrano** [comment]
I have been trying many times but I can't reproduce the crash :-/
It would be very useful if you could give us an stack trace when the app crashes. To get it, follow these steps:
- `make clean` in the root of the SDK
- Run `./configure` adding `--enable-debug` 
- Build the SDK again (`make`)
- Install it: `sudo make install`
- Run `gdb -ex run --args /usr/local/bin/megasimplesync /MyFolder/BACKUP/ /MEGAsync/BACKUP/`
- If the app crashes, you will be in a `(gdb)` prompt
- Enter `bt` and you will see the stack trace. It shows the line of code in which the app has crashed.
- Enter `quit` to exit gdb.

With the full stack trace, it would be easier to fix the bug.
Thanks, Javi.

**Comment by javiserrano** [comment]
We have been unable to reproduce this crash for months.
If anyone can provide extra info or can confirm that the bug still exists in the last version of the `master` branch, we will open it again.

**Comment by rmazitov** [comment]
Megacli sync falls on ui-bg_diagonals-thick_20_666666_40x40.png file
After Posts
Sync - state change of node ui-bg_diagonals-thick_20_666666_40x40.png to Syncing
ui-bg_diagonals-thick_20_666666_40x40.png: Outgoing file transfer starting
Segmentation fault (memory dump)
![ui-bg_diagonals-thick_20_666666_40x40](https://cloud.githubusercontent.com/assets/3483528/22895101/30ba0606-f23d-11e6-81d8-3eaedfe12904.png)
